# Q1

The array is empty and can't be indexed, so trying to access any element in it will throw a `ArrayIndexOutOfBoundsException`.

# Q2

First, the code outputs `before`. Then the exception mentioned in [Q1](#q1) is handled by the `try-catch` block, and inside `catch` the code outputs: `there was something wrong`.

Total output:
```
before
there was something wrong
```

# Q3

Technically, the program doesn't crash since the code correctly handles the exception. The output is same as in [Q2](#q2) and then the exception info, including the Java stack trace of it.

Total output:
```
before
there was something wrong
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
    at <...>
```

# Q4

The first `try` block will print `before1` and then catch the `ArrayIndexOutOfBoundsException` exception, printing `there was something wrong1`.

The second `try` block will not execute and will throw a `java.lang.Error` with something like `exception ArrayIndexOutOfBoundsException has already been caught`.

# Q5

***Exceptions*** are raised in Java with the `throw` keyword. This is useful for managing runtime errors when an unexpected (or expected) condition would otherwise disrupt the program flow.

# Q6

When `mystery()` returns a number like `1` or `0`, the code outputs:
```
here 1
in check
bad y
```
The line `y = y / 0` then causes an `ArithmeticException`, which is handler by a `catch` block that `throws` a `ThingException`.

When `mystery()` returns a string like `oops`, the line `y_int = Integer.parseInt(y)` throws a `NumberFormatException`, so the `catch` block handles it and also throws `ThingException`, with the `check` function never called. Thus the code doesn't output *"in check"*. The output (before throwing the exception) in this case is:
```
here 1
bad y
```

# Q7

Exceptions allow for cleaner code for handling unintended results. They can also handle unpredictable faults outside of the programmer's control: for example, when opening a file (e.g. `new FileReader("file.txt")`), checking with if canâ€™t prevent issues like the file being deleted after the check but before opening.

# Q8

Wrapping a large piece of code (especially something like the whole `main` method) is inefficient in terms of memory and speed, hides where errors occur, makes debugging harder, and prevents specific error handling for different code parts.

# Q9

Anything that is a subclass of `Exception` (except for `RuntimeException` and its subclasses) is a ***checked exception***. The Java compiler forces the programmer to either catch checked exceptions or declare them in the method signature. Other `Exception`s and `Error`s are called ***unchecked exceptions***.

# Q10

All exceptions are subclasses of `Throwable`, and all them except `RuntimeException` and `Error` (and their subclasses) are **checked exceptions**.

# Q11

I/O operations (e.g., reading files) often throw checked exceptions (often outside of the programmer's control, for example, because of something caused by the system or the user), forcing the programmer to handle errors like missing files.

# Q12

```java
import java.io.*;
try (BufferedReader br = new BufferedReader(new FileReader("data.txt"))) {
    String line;
    while ((line = br.readLine()) != null) {
        System.out.println(line);
    }
} catch (IOException e) {
    e.printStackTrace();
}
```

# Q13

```java
try (BufferedWriter bw = new BufferedWriter(new FileWriter("data.txt"))) {
    bw.write("Hello World!\nHow are you?");
} catch (IOException e) {
    e.printStackTrace(); 
}
```

# Q14

Not closing stream buffers may cause ***resource leaks*** (e.g., locked files, memory waste).
